apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kairoflow.fullname" . }}-database-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kairoflow.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.database.host | default "postgres.default.svc.cluster.local" | b64enc | quote }}
  port: {{ .Values.database.port | default "5432" | b64enc | quote }}
  name: {{ .Values.database.name | default "kairoflow" | b64enc | quote }}
  user: {{ .Values.database.user | default "kairoflow" | b64enc | quote }}
  password: {{ .Values.database.password | default "changeme" | b64enc | quote }}