{{- if .Values.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "kairoflow.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}