apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kairoflow.fullname" . }}-openai-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kairoflow.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.openai.apiKey | default "sk-placeholder" | b64enc | quote }}