{{- if .Values.openai.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kairoflow.fullname" . }}-openai-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kairoflow.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.openai.apiKey | b64enc | quote }}
{{- end }}