{{- if .Values.redis.host }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kairoflow.fullname" . }}-redis-secret
  labels:
    {{- include "kairoflow.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.redis.host | b64enc | quote }}
  port: {{ .Values.redis.port | b64enc | quote }}
  {{- if .Values.redis.password }}
  password: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
{{- end }}