apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kairoflow.fullname" . }}-redis-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kairoflow.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.redis.host | default "redis.default.svc.cluster.local" | b64enc | quote }}
  port: {{ .Values.redis.port | default "6379" | b64enc | quote }}
  password: {{ .Values.redis.password | default "" | b64enc | quote }}