{{- if .Values.redis.internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kairoflow.fullname" . }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kairoflow.labels" . | nindent 4 }}
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "kairoflow.selectorLabels" . | nindent 4 }}
    app: redis
{{- end }}